language: ruby
rvm:
- '2.0'
- '2.1'
- '2.2'
env:
- GOPATH=$TRAVIS_BUILD_DIR
services:
- redis-server
before_script:
- mkdir -p ./log
before_install:
- git submodule update --init --recursive
- gem install bundler
install:
- go get github.com/garyburd/redigo/redis
- go get github.com/go-martini/martini
- go get gopkg.in/alecthomas/kingpin.v2
- go get github.com/oguzbilgic/pandik
- bundle install
script: "bundle exec rspec spec && bundle exec rake pact:verify && bundle exec cucumber features && cd src/flapjack && go test -v"
notifications:
  irc:
    channels:
    - irc.freenode.net#flapjack
    template:
    - "%{message} %{repository}#%{build_number} (%{branch} - %{commit} : %{author})"
  slack:
    secure: acjAZ/VdJkR5dw/PyscQPuttG/8+0iVISrw5i0lBrBQ/JjkCYjgBEWun1fQBNWyr5BPDVeZsnqTHD0B7NeuGvGf3VvmkwSAgG1+V+/h89Wr3r8hEDuYI60g2E5N4qMliWZ0xaDj0i9oFgphmxykT/wY02MJZXf32DSFt1FO8G4s=
